In [2]:
import numpy as np

basic

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
a = np.array([1,2,3],dtype = 'int32')
a

array([1, 2, 3])

In [6]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a3 = np.zeros((2,3))
a3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
a4 = np.ones((3,3))
a4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
a5 = np.identity(5)
a5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
a6 = np.arange(5,16)
a6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
a7 = np.linspace(10,20,10)
a7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [14]:
a8 = a7.copy()
a8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [15]:
a9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])