In [1]:
import numpy as np

In [2]:
test = [1,2,3,4,5]
np.array(test)

array([1, 2, 3, 4, 5])

In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
b = np.array([[1,2,3],[2,3,4]])
b

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
b.shape

(2, 3)

In [12]:
b.dtype

dtype('int32')

In [13]:
b.itemsize

4

In [15]:
b.size

6

#accessing /changing specific elements,row,columns

In [18]:
 a = np.array([[1,2,3,4,5],[6,2,7,4,5]])
 a

array([[1, 2, 3, 4, 5],
       [6, 2, 7, 4, 5]])

In [19]:
a[1,3]

4

In [20]:
a[0,:] #all row

array([1, 2, 3, 4, 5])

In [21]:
a[:,0]

array([1, 6])

In [22]:
a[:,2]

array([3, 7])

In [23]:
a[0,1:-1:2]

array([2, 4])

3d example

In [24]:
c = np.array([[[1,2],[3,4]],[[6,2],[5,4]]])
c

array([[[1, 2],
        [3, 4]],

       [[6, 2],
        [5, 4]]])

In [25]:
c[0,1,1]

4

In [26]:
c[:,1,:] = [[9,9],[8,8]]

In [27]:
c

array([[[1, 2],
        [9, 9]],

       [[6, 2],
        [8, 8]]])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((4,2,2),dtype = 'int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [32]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [33]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [34]:
np.random.rand(4,2)

array([[0.17290873, 0.98499984],
       [0.64838005, 0.61688373],
       [0.78368792, 0.14408269],
       [0.33555513, 0.37265497]])

In [35]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
arr = np.array([[1,2,3]])

In [38]:
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [39]:
list1 = [[1,2,3],[1,8,3],[77,2,3]]

In [40]:
list1

[[1, 2, 3], [1, 8, 3], [77, 2, 3]]

In [41]:
list2 = list1

In [42]:
list2

[[1, 2, 3], [1, 8, 3], [77, 2, 3]]

Math

In [44]:
a = np.array([1,2,3,4])

In [45]:
a+2

array([3, 4, 5, 6])

In [46]:
a-2

array([-1,  0,  1,  2])

In [47]:
a*2

array([2, 4, 6, 8])

In [48]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [49]:
b = np.array([1,0,1,0])

In [50]:
a+b

array([2, 2, 4, 4])

In [51]:
a**2

array([ 1,  4,  9, 16])

In [52]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [53]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Algebra

In [54]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [57]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

Statistics

In [60]:
sta= np.array([[1,2,3],[4,5,6]])

In [61]:
np.min(sta)

1

In [62]:
np.max(sta)

6

In [63]:
np.sum(sta,axis=0)

array([5, 7, 9])

#Reorganization

In [64]:
bf = np.array([[1,2,3,4],[4,5,6,7]])
bf

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [65]:
af = bf.reshape(4,2)
af

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])